version: '3' 
services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      # - /app/node_modules
    networks:
      - back_network
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "80:80"
    networks: 
      - back_network
    depends_on:
      - portfolio
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf



networks:
  back_network:
    driver: bridge
